### ISSUE TITLE
can't run server when connected to 3/4G and acting as a wifi hotspot

### ISSUE THREAD

**Issue by makayabou** [many-fac3d-g0d/ServeIt#1]
Hello,

I installed latest version of Servlet with F-Droid. 
I'm using my 3/4G connection on my android phone, and would like to share files by http, with other devices that are connected by wifi to my android phone, which acts as a wifi hotspot.

Why is it necessary to be connected to a wifi network to run Servlet ? Is there any way to bypass this limitation? 

Thanks

**Comment by many-fac3d-g0d** [comment]
@makayabou I'm able to reproduce the scenario. The issue happens due to the wifiIPv4 value coming as null when the hotspot is turned on from android. Can you send me the screenshot of ip address value from the Settings of android phone, like below to confirm

![Screenshot_20211017_194550](https://user-images.githubusercontent.com/54078651/137631453-687a6a22-0b55-46d0-834a-3a3d095057ab.jpg)

Thanks.

**Comment by ghost** [comment]
I believe that i because it only scan the ip4 address. (The issue seems cause [this line](https://github.com/many-fac3d-g0d/ServeIt/blob/c547bc59ae2a59fe840ef6dd8e14ea2e9536f428/lib/main.dart#L116))

ServeIt should run on wifi, hotspot or even without any connection (localhost).

For example, when i run `ifconfig` with hotspot i does provide my an ip address:
![Screenshot_20211022_121500](https://user-images.githubusercontent.com/88058138/138437454-49378bb0-c6b3-4560-9f39-a62a548904b5.jpg)

**Comment by ghost** [comment]
The server runs only if ip4 is available.
This check should be deleted: [this line](https://github.com/many-fac3d-g0d/ServeIt/blob/c547bc59ae2a59fe840ef6dd8e14ea2e9536f428/lib/main.dart#L151)
`
if(wifiIPv4 != null){ // wifiName can be null sometimes, hence using ip to decide start the server 
`

But technically it should work perfect with or without wifi.

It can even work on **localhost** :)

**Comment by many-fac3d-g0d** [comment]
@cloneconf thanks for the suggestion. But using localhost in Android has some issues. Check the below link.
[flutter localhost](https://stackoverflow.com/questions/47372568/how-to-point-to-localhost8000-with-the-dart-http-package-in-flutter)

Cant start the server with localhost (link will not be accesible from other devices). Although im trying for a workaround to fetch the ip when hotspot is on.

**Comment by ghost** [comment]
@many-fac3d-g0d I find a solution !

I used [NetworkInterface](https://api.dart.dev/stable/2.14.4/dart-io/NetworkInterface-class.html) to get the ips.

It return all the connection, and return an empty list when there isn't.

**Here is a video:**
(Note that i am hidding the ips cuz they are my real ips!)
https://user-images.githubusercontent.com/88058138/139555647-0b0496b4-1e44-41f3-88f4-100fab763e90.mp4

**The code is here:**
[https://gist.github.com/cloneconf/2b0b9b1bf65791d9c6b2389e1da278bb](https://gist.github.com/cloneconf/2b0b9b1bf65791d9c6b2389e1da278bb)

**Comment by ghost** [comment]
Also previously i wanted to achieve the same thing, you can see:

(Actually it is the same idea of you)
[https://github.com/cloneconf/filesh-flutter/blob/master/lib/home.dart](https://github.com/cloneconf/filesh-flutter/blob/master/lib/home.dart)

I hope you find it useful.

**Comment by ghost** [comment]
When it's localhost, we can simply use **0.0.0.0** "[Listens on "any IP" (0.0.0.0) instead of loop-back (localhost, 127.0.0.1) to allow remote connections.](https://github.com/dart-lang/samples/tree/master/server/simple#readme)" in shelf.

**Comment by many-fac3d-g0d** [comment]
dda393f addresses the wifi hotspot ip handling, the update will be available in fdroid in couple of days. @makayabou and @cloneconf thanks for your help 😁
